In [1]:
import pandas as pd

In [2]:
# 1. Loading a CSV dataset into a Pandas DataFrame
df = pd.read_csv("D:\\New folder\\celebal\\assignment 1\\Combined_dataset.csv")
df

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,"""₹3,995.00""",INR,http://assets.myntassets.com/assets/images/837...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,"{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",NaN,NaN,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",NaN,NaN,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",NaN,NaN,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,13698258,KREDO,Men FORTE Silver Automatic Skeleton Analogue W...,3.5,11,11890,50.0,"""₹11,890.00""",INR,http://assets.myntassets.com/assets/images/136...,...,"{""1_star"":3,""2_stars"":0,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""pi-13698258""]",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
996,16896006,GUESS,Women White Patterned Dial & White Straps Anal...,5.0,22,8900,45.0,"""₹8,900.00""",INR,http://assets.myntassets.com/assets/images/168...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-16896006_cae700"",""https://videos.myntasse...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
997,1708108,GIORDANO,Women Rose Gold-Toned Mirrored Analogue Watch ...,2.8,5,7950,50.0,"""₹7,950.00""",INR,http://assets.myntassets.com/assets/images/170...,...,"{""1_star"":2,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]",NaN,NaN,"[{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
998,19280114,Fastrack,Men Black Brass Dial & Black Stainless Steel S...,4.3,17,3295,20.0,"""₹2,636.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":1,""2_stars"":2,""3_stars"":0,""4_stars"":...",NaN,Tru███m R███il,"[{""size"":""Onesize""}]",NaN,Sho███o. ███-10█████████enu███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches
999,18601682,BOLDFIT,Purple Textured Yoga Mat,3.8,161,699,31.0,"""₹699.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":24,""2_stars"":8,""3_stars"":22,""4_stars...",NaN,NaN,"[{""size"":""Medium""}]",NaN,NaN,"[{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",yoga-mats

In [3]:
# 2. Exploring Data
df.head()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,"""₹3,995.00""",INR,http://assets.myntassets.com/assets/images/837...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,"{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",NaN,NaN,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",NaN,NaN,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",NaN,NaN,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe

In [4]:
df.tail()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
995,13698258,KREDO,Men FORTE Silver Automatic Skeleton Analogue W...,3.5,11,11890,50.0,"""₹11,890.00""",INR,http://assets.myntassets.com/assets/images/136...,...,"{""1_star"":3,""2_stars"":0,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""pi-13698258""]",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
996,16896006,GUESS,Women White Patterned Dial & White Straps Anal...,5.0,22,8900,45.0,"""₹8,900.00""",INR,http://assets.myntassets.com/assets/images/168...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-16896006_cae700"",""https://videos.myntasse...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
997,1708108,GIORDANO,Women Rose Gold-Toned Mirrored Analogue Watch ...,2.8,5,7950,50.0,"""₹7,950.00""",INR,http://assets.myntassets.com/assets/images/170...,...,"{""1_star"":2,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]",NaN,NaN,"[{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
998,19280114,Fastrack,Men Black Brass Dial & Black Stainless Steel S...,4.3,17,3295,20.0,"""₹2,636.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":1,""2_stars"":2,""3_stars"":0,""4_stars"":...",NaN,Tru███m R███il,"[{""size"":""Onesize""}]",NaN,Sho███o. ███-10█████████enu███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches
999,18601682,BOLDFIT,Purple Textured Yoga Mat,3.8,161,699,31.0,"""₹699.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":24,""2_stars"":8,""3_stars"":22,""4_stars...",NaN,NaN,"[{""size"":""Medium""}]",NaN,NaN,"[{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",yoga-mats

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 24 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   product_id              1000 non-null   int64
 1   title                   1000 non-null   str
 2   product_description     1000 non-null   str
 3   rating                  1000 non-null   float64
 4   ratings_count           1000 non-null   int64
 5   initial_price           1000 non-null   int64
 6   discount                879 non-null    float64
 7   final_price             1000 non-null   str
 8   currency                1000 non-null   str
 9   images                  1000 non-null   str
 10  delivery_options        1000 non-null   str
 11  product_details         1000 non-null   str
 12  breadcrumbs             1000 non-null   str
 13  product_specifications  1000 non-null   str
 14  amount_of_stars         1000 non-null   str
 15  what_customers_said     427 non-null    str
 16  seller_name             699 non-null    str
 17  sizes                   1000 non-null   str
 18  videos                  219 non-null    str
 19  seller_information      699 non-null    str
 20  variations              438 non-null    str
 21  best_offer              1000 non-null   str
 22  more_offers             1000 non-null   str
 23  category                1000 non-null   str
dtypes: float64(2), int64(3), str(19)
memory usage: 187.6 KB

In [6]:
df.describe()

         product_id     rating  ratings_count  initial_price    discount
count  1.000000e+03  1000.0000    1000.000000     1000.00000  879.000000
mean   1.713437e+07     3.6215      76.691000     2723.24100   53.503982
std    3.813766e+06     1.3744     241.114263     2408.69736   18.029201
min    5.868460e+05     0.0000       0.000000      249.00000    1.000000
25%    1.511501e+07     3.7000       7.000000     1399.00000   44.000000
50%    1.820890e+07     4.1000      17.000000     1999.00000   56.000000
75%    1.902737e+07     4.3000      58.000000     3299.00000   66.000000
max    2.274707e+07     5.0000    4441.000000    22199.00000   88.000000

In [7]:
df.dtypes

product_id                  int64
title                         str
product_description           str
rating                    float64
ratings_count               int64
initial_price               int64
discount                  float64
final_price                   str
currency                      str
images                        str
delivery_options              str
product_details               str
breadcrumbs                   str
product_specifications        str
amount_of_stars               str
what_customers_said           str
seller_name                   str
sizes                         str
videos                        str
seller_information            str
variations                    str
best_offer                    str
more_offers                   str
category                      str
dtype: object

In [8]:
df.shape

(1000, 24)

In [9]:
df.columns

Index(['product_id', 'title', 'product_description', 'rating', 'ratings_count',
       'initial_price', 'discount', 'final_price', 'currency', 'images',
       'delivery_options', 'product_details', 'breadcrumbs',
       'product_specifications', 'amount_of_stars', 'what_customers_said',
       'seller_name', 'sizes', 'videos', 'seller_information', 'variations',
       'best_offer', 'more_offers', 'category'],
      dtype='str')

In [10]:
# 3. Handling missing values
df.isnull().sum()

product_id                  0
title                       0
product_description         0
rating                      0
ratings_count               0
initial_price               0
discount                  121
final_price                 0
currency                    0
images                      0
delivery_options            0
product_details             0
breadcrumbs                 0
product_specifications      0
amount_of_stars             0
what_customers_said       573
seller_name               301
sizes                       0
videos                    781
seller_information        301
variations                562
best_offer                  0
more_offers                 0
category                    0
dtype: int64

In [11]:
df["discount"] = df["discount"].fillna(0)
df["seller_name"] = df["seller_name"].fillna("Unknown")
df["seller_information"] = df["seller_information"].fillna("Not Available")
df["variations"] = df["variations"].fillna("No Variations")
df

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,"""₹3,995.00""",INR,http://assets.myntassets.com/assets/images/837...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...",NaN,Unknown,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",Not Available,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,"{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",NaN,Unknown,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",Not Available,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",NaN,Unknown,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",Not Available,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",NaN,Unknown,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",Not Available,No Variations,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,Unknown,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",NaN,Not Available,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,13698258,KREDO,Men FORTE Silver Automatic Skeleton Analogue W...,3.5,11,11890,50.0,"""₹11,890.00""",INR,http://assets.myntassets.com/assets/images/136...,...,"{""1_star"":3,""2_stars"":0,""3_stars"":2,""4_stars"":...",NaN,Unknown,"[{""size"":""Onesize""}]","[""pi-13698258""]",Not Available,No Variations,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
996,16896006,GUESS,Women White Patterned Dial & White Straps Anal...,5.0,22,8900,45.0,"""₹8,900.00""",INR,http://assets.myntassets.com/assets/images/168...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,Unknown,"[{""size"":""Onesize""}]","[""rw-16896006_cae700"",""https://videos.myntasse...",Not Available,No Variations,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
997,1708108,GIORDANO,Women Rose Gold-Toned Mirrored Analogue Watch ...,2.8,5,7950,50.0,"""₹7,950.00""",INR,http://assets.myntassets.com/assets/images/170...,...,"{""1_star"":2,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,Unknown,"[{""size"":""Onesize""}]",NaN,Not Available,"[{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
998,19280114,Fastrack,Men Black Brass Dial & Black Stainless Steel S...,4.3,17,3295,20.0,"""₹2,636.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":1,""2_stars"":2,""3_stars"":0,""4_stars"":...",NaN,Tru███m R███il,"[{""size"":""Onesize""}]",NaN,Sho███o. ███-10█████████enu███████████████████...,No Variations,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches
999,18601682,BOLDFIT,Purple Textured Yoga Mat,3.8,161,699,31.0,"""₹699.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":24,""2_stars"":8,""3_stars"":22,""4_stars...",NaN,Unknown,"[{""size"":""Medium""}]",NaN,Not Available,"[{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",yoga-mats

In [12]:
df = df.drop(columns=['what_customers_said', 'videos'])

In [13]:
df.isnull().sum()

product_id                0
title                     0
product_description       0
rating                    0
ratings_count             0
initial_price             0
discount                  0
final_price               0
currency                  0
images                    0
delivery_options          0
product_details           0
breadcrumbs               0
product_specifications    0
amount_of_stars           0
seller_name               0
sizes                     0
seller_information        0
variations                0
best_offer                0
more_offers               0
category                  0
dtype: int64

In [14]:
# 4. 4 Performing basic operations
df.columns

Index(['product_id', 'title', 'product_description', 'rating', 'ratings_count',
       'initial_price', 'discount', 'final_price', 'currency', 'images',
       'delivery_options', 'product_details', 'breadcrumbs',
       'product_specifications', 'amount_of_stars', 'seller_name', 'sizes',
       'seller_information', 'variations', 'best_offer', 'more_offers',
       'category'],
      dtype='str')

In [15]:
df[['title', 'initial_price', 'discount']]

              title  initial_price  discount
0       Lino Perros           3995      58.0
1    Tommy Hilfiger           2899      35.0
2             Lavie           2999      65.0
3            F Gear           1675      52.0
4         MYTRIDENT           2899      17.0
..              ...            ...       ...
995           KREDO          11890      50.0
996           GUESS           8900      45.0
997        GIORDANO           7950      50.0
998        Fastrack           3295      20.0
999         BOLDFIT            699      31.0

[1000 rows x 3 columns]

In [16]:
df[['title', 'initial_price', 'rating']][df['discount']>75]

                         title  initial_price  rating
16               DREAM WEAVERZ           2599     3.8
17                      Arrabi           6329     4.3
18                     Kastner           1399     3.8
21                     Mactree           9060     3.9
38                   KARATCART           3397     4.6
..                         ...            ...     ...
925               Dennis Lingo           3099     3.8
963                    BULLMER           3998     4.8
965  AMERICAN EAGLE OUTFITTERS           1799     4.4
976                 Art Street           3500     3.9
990                  TIMESMITH           2499     3.7

[69 rows x 3 columns]

In [19]:
df[(df['rating']>4.2) & (df['initial_price']<2500) & (df['discount']>60)]

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,breadcrumbs,product_specifications,amount_of_stars,seller_name,sizes,seller_information,variations,best_offer,more_offers,category
52,22436508,Bruchi CLUB,Men Low-Rise Anti-Bacterial Basic Briefs,5.0,4,888,65.0,"""₹310.00""",INR,http://assets.myntassets.com/assets/images/224...,...,"[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Assorted"",""specificati...","{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",BRU███ CL███APP█████████ATE█████████,"[{""size"":""S"",""value"":""28.0in"",""value_name"":""To...",A-2███NOI███SEC█████████AUT███████████████████...,No Variations,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",briefs
57,16281444,Bharatasya,Women White & Black Woolen Earwarmer Headband,4.3,7,699,68.0,"""₹223.00""",INR,http://assets.myntassets.com/assets/images/162...,...,"[{""name"":""Accessories"",""url"":""https://www.mynt...","[{""specification_name"":""Character"",""specificat...","{""1_star"":0,""2_stars"":0,""3_stars"":1,""4_stars"":...",VR ███ign███,"[{""size"":""Onesize"",""value"":""16.0in"",""value_nam...",Vil███agl███Waz█████████a G███████████████████...,No Variations,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",caps
107,18962984,Athena,Burgundy Off-Shoulder Scrunchie Bodycon Dress,4.3,236,2499,68.0,"""₹799.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":23,""2_stars"":5,""3_stars"":15,""4_stars...",APE███PPA███S,"[{""size"":""XS"",""value"":""8.0in"",""value_name"":""Sl...","Plo███o. ███, P█████████2Se███████████████████...","[{},{},{}]","{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses
128,17692718,Style Quotient,Women Tranquil Teal Solid Halter Neck Dress,4.8,8,1599,69.0,"""₹495.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",Kri███n S███het█████████td,"[{""size"":""S"",""value"":""34.0in"",""value_name"":""To...","615███hur███ate█████████,5 ███████████████████...",No Variations,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses
129,17194598,Tokyo Talkies,Women Charming Purple Solid Dress,4.3,48,1749,65.0,"""₹437.00""",INR,http://assets.myntassets.com/assets/images/171...,...,"[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":3,""2_stars"":1,""3_stars"":4,""4_stars"":...",Vis███ St███,"[{""size"":""XS"",""value"":""32.0in"",""value_name"":""B...",3rd███oor███o. █████████Mai███████████████████...,No Variations,"{""applicable_on"":""Orders above Rs. 449 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses
133,18996672,Bella Moda,Girls Yellow & Navy Blue Fit and Flare Dress,4.6,8,2017,70.0,"""₹605.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",SHI███TRA███S,"[{""size"":""1-2Y"",""value"":""21.0in"",""value_name"":...","642███H F███R,J█████████LIS███████████████████...",No Variations,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses
143,10691426,SASSAFRAS,Black & Beige Ikat Print Cotton Shirt Dress,4.5,4441,2199,65.0,"""₹769.00""",INR,http://assets.myntassets.com/assets/images/106...,...,"[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":126,""2_stars"":78,""3_stars"":288,""4_st...",ARD███ Re███l C███,"[{""size"":""XS"",""value"":""32.0in"",""value_name"":""T...",Khe███ No███76/█████████il ███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 749 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses
145,18963006,Athena,Purple Off-Shoulder Scrunchie Bodycon Dress,4.3,45,2499,68.0,"""₹799.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":2,""2_stars"":1,""3_stars"":3,""4_stars"":...",APE███PPA███S,"[{""size"":""XS"",""value"":""8.0in"",""value_name"":""Sl...","Plo███o. ███, P█████████2Se███████████████████...","[{},{},{}]","{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses
155,20046216,YK Disney,Girls Minnie Mouse Graphic Printed A-Line T-sh...,5.0,7,999,67.0,"""₹329.00""",INR,http://assets.myntassets.com/assets/images/200...,...,"[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",CRO███OAD███LOT█████████LTD███,"[{""size"":""2-3Y"",""value"":""23.0in"",""value_name"":...",75/███eer███gar█████████ Ha███████████████████...,No Variations,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses
169,13406942,Global Desi,Girls Blue Embroidered A-Line Denim Dress,4.8,8,1799,75.0,"""₹449.00""",INR,http://assets.myntassets.com/assets/images/134...,...,"[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":0,""2_stars"":0,""3_stars"":1,""4_stars"":...",OCH███AND███ACK█████████LIM██████,"[{""size"":""3-4Y"",""value"":""21.0in"",""value_name"":...",Bui███ng ███rat█████████eam███████████████████...,No Variations,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses
171,13387582,Wish Karo,Girls Black Polka Dot Printed Fit and Flare Dress,4.7,18,2123,65.0,"""₹743.00""",INR,http://assets.myntassets.com/assets/images/133...,...,"[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",Kot███da ███est█████████Ltd███,"[{""size"":""0-3M"",""value"":""18.6in"",""value_name"":...","LL ███3, ███den█████████adu███████████████████...",No Variations,"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses
178,13449506,DOOR74,Women Black Solid Maxi Dress,5.0,7,2399,70.0,"""₹719.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",JXP███S,"[{""size"":""S"",""value"":""7.0in"",""value_name"":""Sle...",D74███D F███ANE█████████Noi███████████████████...,No Variations,"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses
202,12999996,Vishudh,Women Navy Blue Checked Dupatta,4.6,17,599,62.0,"""₹227.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Border"",""specification...","{""1_star"":0,""2_stars"":1,""3_stars"":1,""4_stars"":...",Fla███tar███mme██████,"[{""size"":""Onesize""}]","1st███oor███abi█████████02,███████████████████...",No Variations,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",dupatta
209,10564232,PRITA BY PRIYAASI,Multicoloured Gold-Plated Beaded Handcrafted C...,4.3,727,1130,69.0,"""₹350.00""",INR,http://assets.myntassets.com/assets/images/105...,...,"[{""name"":""Accessories"",""url"":""https://www.mynt...","[{""specification_name"":""Base Metal"",""specifica...","{""1_star"":48,""2_stars"":26,""3_stars"":62,""4_star...",PRI███DES███S P█████████MIT███,"[{""size"":""Onesize""}]",PRI███DES███S P█████████MIT███████████████████...,No Variations,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",earrings
217,20041906,KARATCART,Women Black Oxidised Classic Drop Earrings,4.3,9,1730,65.0,"""₹605.00""",INR,http://assets.myntassets.com/assets/images/200...,...,"[{""name"":""Accessories"",""url"":""https://www.mynt...","[{""specification_name"":""Base Metal"",""specifica...","{""1_star"":0,""2_stars"":1,""3_stars"":1,""4_stars"":...",KOK███V G███AL █████████,"[{""size"":""Onesize""}]",Sho███58-███Sec█████████ain███████████████████...,No Variations,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",earrings
220,22601952,SOHI,Gold Plated Teardrop Shaped Drop Earrings,4.5,15,1455,76.0,"""₹349.00""",INR,http://assets.myntassets.com/assets/images/226...,...,"[{""name"":""Accessories"",""url"":""https://www.mynt...","[{""specification_name"":""Base Metal"",""specifica...","{""1_star"":0,""2_stars"":1,""3_stars"":1,""4_stars"":...",Bil███nka███Pri█████████ted███,"[{""size"":""Onesize""}]",117███IND███RIA█████████ II███████████████████...,No Variations,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",earrings
224,14399558,Shoshaa,Silver-Plated & Pink Oxidised Drop Earrings,4.6,21,2488,72.0,"""₹696.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"[{""name"":""Accessories"",""url"":""https://www.mynt...","[{""specification_name"":""Base Metal"",""specifica...","{""1_star"":1,""2_stars"":0,""3_stars"":1,""4_stars"":...",SHO███A D███GNS██████,"[{""size"":""Onesize""}]","C/1███, 1███Plo█████████loc███████████████████...","[{},{}]","{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",earrings
249,19990734,VASTRAMAY,Girls Mustard Yellow Chikankari Cotton Ethnic ...,4.7,9,2499,61.0,"""₹974.00""",INR,http://assets.myntassets.com/assets/images/199...,...,"[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",Vas███may███t. ██████,"[{""size"":""2-3Y"",""value"":""9.5in"",""value_name"":""...",59A███ATH███AR █████████Kol███████████████████...,"[{},{},{},{},{}]","{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",ethnic-dresses
422,21184968,HERE&NOW,Women Flared Heavy Fade Stretchable Jeans,4.6,111,2399,68.0,"""₹767.00""",INR,http://assets.myntassets.com/assets/images/211...,...,"[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":1,""2_stars"":2,""3_stars"":7,""4_stars"":...",Omn███ch ███ail███,"[{""size"":""26"",""value"":""26.0in"",""value_name"":""T...","11t███loo███Fla█████████6, ███████████████████...",No Variations,"{""applicable_on"":""Orders above Rs. 749 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",jeans
480,13428018,ETC,Women Brown & Navy Blue Pure Cotton Striped Lo...,4.3,189,799,70.0,"""₹559.00""",INR,http://assets.myntassets.com/assets/images/134...,...,"[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Body or Garment Size"",...","{""1_star"":7,""2_stars"":5,""3_stars"":21,""4_stars""...",Tru███t C███erc███,"[{""size"":""S"",""value"":""34.0in"",""value_name"":""To...",1 s███loo███Cab█████████-01███████████████████...,No Variations,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",lounge-tshirts
489,15973760,Zoom Minimondo,Unisex Kids Magenta & Blue Pure Cotton Night suit,4.8,10,1299,69.0,"""₹402.00""",INR,http://assets.myntassets.com/assets/images/159...,...,"[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Body or Garment Size"",...","{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",KCJ███RKE███G P█████████MIT███,"[{""size"":""7-8Y"",""value"":""34.0in"",""value_name"":...",SAD███D D███AVA█████████OP ███████████████████...,No Variations,"{""applicable_on"":""Orders above Rs. 599 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",night-suits
507,15294314,Zaveri Pearls,Set of 2 Rose Gold Plated CZ-Studded Contempor...,4.4,27,1995,82.0,"""₹359.00""",INR,http://assets.myntassets.com/assets/images/152...,...,"[{""name"":""Accessories"",""url"":""https://www.mynt...","[{""specification_name"":""Base Metal"",""specifica...","{""1_star"":1,""2_stars"":0,""3_stars"":4,""4_stars"":...",ZAV███ PE███S,"[{""size"":""Onesize""}]","12,███T F███R, █████████LDG███████████████████...",No Variations,"{""applicable_on"":""Orders above Rs. 1299 (only ...","[{""offer_name"":""10% Instant Discount on Citi C...",ring
510,10018911,SEJ by Nisha Gupta,Multicoloured Printed Table Runner,4.5,13,1849,70.0,"""₹554.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"[{""name"":""Unisex"",""url"":""https://www.myntra.co...","[{""specification_name"":""Material"",""specificati...","{""1_star"":1,""2_stars"":0,""3_stars"":0,""4_stars"":...",SEJ███RNI███NGS█████████LIM██████,"[{""size"":""Onesize""}]",K-1███ST ███OR █████████AGA███████████████████...,No Variations,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",runners
542,16293500,BELLEZIYA,Women Blue & White Printed Scarf,4.3,3,1249,65.0,"""₹437.00""",INR,http://assets.myntassets.com/assets/images/162...,...,"[{""name"":""Accessories"",""url"":""https://www.mynt...","[{""specification_name"":""Border"",""specification...","{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",BEA███ LI███TYL█████████,"[{""size"":""Onesize"",""value"":""70.0in"",""value_nam...",BEA███ LI███TYL█████████DB-███████████████████...,No Variations,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",scarves
543,16293432,BELLEZIYA,Women Blue & White Tie & Dye Dyed Scarf,4.7,6,1499,65.0,"""₹524.00""",INR,http://assets.myntassets.com/assets/images/162...,...,"[{""name"":""Accessories"",""url"":""https://www.mynt...","[{""specification_name"":""Border"",""specification...","{""1_star"":0,""2_stars"":0,""3_stars"":1,""4_stars"":...",BEA███ LI███TYL█████████,"[{""size"":""Onesize"",""value"":""70.0in"",""value_nam...",BEA███ LI███TYL█████████DB-███████████████████...,No Variations,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",scarves
555,18960188,The Indian Garage Co,Men White & Charcoal Grey Printed Cotton Casua...,4.4,35,1749,74.0,"""₹454.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":2,""2_stars"":1,""3_stars"":1,""4_stars"":...",THE███DIA███ARA█████████,"[{""size"":""38"",""value"":""38.5in"",""value_name"":""C...",2/1███rve███o.4█████████hal███████████████████...,"[{},{},{}]","{""applicable_on"":""Orders above Rs. 749 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",shirts
560,18960086,The Indian Garage Co,Men Green Slim Fit Horizontal Stripes Casual S...,4.5,23,1749,72.0,"""₹454.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":0,""2_stars"":1,""3_stars"":2,""4_stars"":...",THE███DIA███ARA█████████Y -██████,"[{""size"":""38"",""value"":""38.5in"",""value_name"":""C...","No.███1, ███ur █████████lur█████████████████████8","[{},{},{},{},{}]","{""applicable_on"":""Orders above Rs. 749 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",shirts
573,21388884,French Connection,Slim Fit Striped Cotton Casual Shirt,4.3,58,2199,70.0,"""₹2,199.00""",INR,http://assets.myntassets.com/assets/images/213...,...,"[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":0,""2_stars"":6,""3_stars"":5,""4_stars"":...",Unknown,"[{""size"":""38"",""value"":""40.25in"",""value_name"":""...",Not Available,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",shirts
626,13453254,DENNISON,Men Mauve Smart Slim Fit Solid Cotton Linen Ca...,4.6,7,2199,74.0,"""₹2,199.00""",INR,http://assets.myntassets.com/assets/images/134...,...,"[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":0,""2_stars"":0,""3_stars"":1,""4_stars"":...",Unknown,"[{""size"":""38"",""value"":""40.0in"",""value_name"":""C...",Not Available,"[{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",shirts
628,18690268,Dennis Lingo,Men Slim Fit Tropical Casual Shirt,4.6,5,1999,80.0,"""₹1,999.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":0,""2_stars"":0,""3_stars"":1,""4_stars"":...",Unknown,"[{""size"":""38"",""value"":""39.0in"",""value_name"":""C...",Not Available,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",shirts
643,19999300,Dennis Lingo,Men Navy Blue Slim Fit Tartan Checked Casual S...,4.4,16,2499,74.0,"""₹2,499.00""",INR,http://assets.myntassets.com/assets/images/199...,...,"[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":0,""2_stars"":0,""3_stars"":4,""4_stars"":...",Unknown,"[{""size"":""38"",""value"":""39.0in"",""value_name"":""C...",Not Available,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",shirts
650,18947596,KASSUALLY,Women Green Slim Fit Denim Outdoor Denim Shorts,4.7,9,1799,67.0,"""₹593.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Body or Garment Size"",...","{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",Khu███r A███arl███,"[{""size"":""26"",""value"":""31.5in"",""value_name"":""H...","2- ███OR,███-22█████████PLE███████████████████...",[{}],"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",shorts
669,18947600,KASSUALLY,Women White Printed Slim Fit High-Rise Denim O...,4.7,38,1899,66.0,"""₹645.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Body or Garment Size"",...","{""1_star"":0,""2_stars"":2,""3_stars"":0,""4_stars"":...",Khu███r A███arl█████████,"[{""size"":""26"",""value"":""30.5in"",""value_name"":""H...",KHA███ NO███85/█████████Vih███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",shorts
677,17367634,Berrylush,Black Animal Printed Wrap it Up Skirt,4.3,43,1399,74.0,"""₹363.00""",INR,http://assets.myntassets.com/assets/images/173...,...,"[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":4,""2_stars"":0,""3_stars"":3,""4_stars"":...",Sup███om ███,"[{""size"":""26"",""value"":""17.5in"",""value_name"":""S...",Plo███o- ███ 1s█████████Sui███████████████████...,No Variations,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",skirts

In [20]:
df.iloc[:, [0,6]]

     product_id  discount
0       8376765      58.0
1       9136281      35.0
2      17633752      65.0
3       1376949      52.0
4      13939916      17.0
..          ...       ...
995    13698258      50.0
996    16896006      45.0
997     1708108      50.0
998    19280114      20.0
999    18601682      31.0

[1000 rows x 2 columns]

In [21]:
df.iloc[0:6, 1:4]

            title                         product_description  rating
0     Lino Perros              Women Navy Blue Solid Backpack     3.8
1  Tommy Hilfiger           Unisex Navy Blue Striped Backpack     4.5
2           Lavie              Aries Women Pink Mini Backpack     4.4
3          F Gear  Unisex Navy & Grey Printed Burner Backpack     4.4
4       MYTRIDENT                    Men Blue Solid Bath Robe     4.7
5             H&M  Beige & Tan Solid Stoneware Soap Dispenser     4.5

In [22]:
# 5. Removing duplicates
df.duplicated().sum()

np.int64(0)

In [23]:
# 6. Create a derived column  (savings = price * discount/100)
df['savings'] = df['initial_price'] * df['discount']/100
df

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,product_specifications,amount_of_stars,seller_name,sizes,seller_information,variations,best_offer,more_offers,category,savings
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,"""₹3,995.00""",INR,http://assets.myntassets.com/assets/images/837...,...,"[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...",Unknown,"[{""size"":""Onesize""}]",Not Available,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,2317.10
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,"[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",Unknown,"[{""size"":""Onesize""}]",Not Available,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,1014.65
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",Unknown,"[{""size"":""S""}]",Not Available,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,1949.35
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"[{""specification_name"":""Compartment Closure"",""...","{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",Unknown,"[{""size"":""Onesize""}]",Not Available,No Variations,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,871.00
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"[{""specification_name"":""Body or Garment Size"",...","{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",Unknown,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",Not Available,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe,492.83
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,13698258,KREDO,Men FORTE Silver Automatic Skeleton Analogue W...,3.5,11,11890,50.0,"""₹11,890.00""",INR,http://assets.myntassets.com/assets/images/136...,...,"[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":3,""2_stars"":0,""3_stars"":2,""4_stars"":...",Unknown,"[{""size"":""Onesize""}]",Not Available,No Variations,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches,5945.00
996,16896006,GUESS,Women White Patterned Dial & White Straps Anal...,5.0,22,8900,45.0,"""₹8,900.00""",INR,http://assets.myntassets.com/assets/images/168...,...,"[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",Unknown,"[{""size"":""Onesize""}]",Not Available,No Variations,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches,4005.00
997,1708108,GIORDANO,Women Rose Gold-Toned Mirrored Analogue Watch ...,2.8,5,7950,50.0,"""₹7,950.00""",INR,http://assets.myntassets.com/assets/images/170...,...,"[{""specification_name"":""Dial Material"",""specif...","{""1_star"":2,""2_stars"":1,""3_stars"":0,""4_stars"":...",Unknown,"[{""size"":""Onesize""}]",Not Available,"[{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches,3975.00
998,19280114,Fastrack,Men Black Brass Dial & Black Stainless Steel S...,4.3,17,3295,20.0,"""₹2,636.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":1,""2_stars"":2,""3_stars"":0,""4_stars"":...",Tru███m R███il,"[{""size"":""Onesize""}]",Sho███o. ███-10█████████enu███████████████████...,No Variations,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches,659.00
999,18601682,BOLDFIT,Purple Textured Yoga Mat,3.8,161,699,31.0,"""₹699.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"[{""specification_name"":""Mat Thickness"",""specif...","{""1_star"":24,""2_stars"":8,""3_stars"":22,""4_stars...",Unknown,"[{""size"":""Medium""}]",Not Available,"[{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",yoga-mats,216.69

In [24]:
# 7. Saving the cleaned dataset as a new CSV file
df.to_csv("Cleaned_dataset.csv", index=False)